# Generated by Django 2.2.16 on 2020-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user_feedback", "0004_auto_20200219_2143")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(blank=True, max_length=2000, null=True),
        )
    ]
